# config/nav-list.yaml
# App\Controller\ShowController is the default controller unless otherwise specified
# Custom controllers inherit from App\Controller\ShowController
navItems:
  - name: Home
  - name: Navigation 2
    route: nav-2
  - name: Nav three
    route: nav-3
  - name: Foo
    route: foo
    controller: App\Controller\FooController::foo
  - name: Bar
    route: bar
